# Generated by Django 3.2.9 on 2021-12-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0002_events_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusteam',
            name='role',
            field=models.CharField(choices=[('MAIN', 'MAIN'), ('DIRECTORS', 'DIRECTORS'), ('WEBMASTERS', 'WEBMASTERS'), ('LEADS', 'LEADS')], default='LEADS', max_length=10),
        ),
    ]
