# Generated by Django 3.2.9 on 2021-12-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0003_alter_focusteam_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusteam',
            name='groupName',
            field=models.CharField(choices=[('MAIN', 'MAIN'), ('DIRECTORS', 'DIRECTORS'), ('WEBMASTERS', 'WEBMASTERS'), ('LEADS', 'LEADS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='focusteam',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
