# Generated by Django 3.2.9 on 2022-01-30 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0005_auto_20211207_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologyclubs',
            name='clubLogo',
        ),
    ]
