# Generated by Django 3.2.9 on 2022-01-30 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0006_remove_technologyclubs_clublogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='technologyclubs',
            name='clubLogo',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
